(declare-const X Int)
(declare-const Y Int)
(declare-const Z Int)
(declare-const A Int)
(declare-const B Int)
(declare-const W Int)
(assert (> X Y 0))
(assert (> Z W 0))
(assert (and (>= A 0) (>= B 0)))
(assert (> (- X Y) (- Z W)))
(assert (= (+ X Y A) (+ Z W B)))
(assert (<= (/ X (+ X Y)) (/ Z (+ Z W))))
(check-sat)
(get-model)
